name: actions workflow

on: [push]

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple-action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Michael
      - name: Log greet time
        uses: echo "${{ steps.greet.outputs.time }}"