name: derp

on: 
  repository_dispatch:
    types: [derp]
  push:
    branches:
      - 'test'
    
  # schedule:
  #   - cron: "0/5 * * * *"

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        id: setup-java
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Set up Maven
        id: setup-maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: maven install 
        id: maven-install
        run: |
          mvn clean install
      - name: list 
        id: list all files after install 
        run: ls -a

      
  
