name: derp

on: 
  repository_dispatch:
    types: [derp]
  push:
    
  # schedule:
  #   - cron: "0/5 * * * *"

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: list files
        run: |
          pwd
          ls -a
  run-shell:
    runs-on: ubuntu-latest
    steps:
      - name: check java version
        run: java --version
      - name: print username
        run: echo "mwilliams705"
      - name: python script
        run:  |
          import platform
          print(platform.processor())
        shell: python

      
  
