name: test

on: 
  repository_dispatch:
    types: [test]
  push:
    
  # schedule:
  #   - cron: "0/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        id: setup-java
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Set up Maven
        id: setup-maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: maven install 
        id: maven-install
        run: |
          mvn clean package
      - name: list
        run: |
          ls -a
          cd ./target ** ls -a

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mwilliams705/spabackend:latest
         

      
  
